-- Chakudya Nutrition Registry
-- Migration: drug_nutrient_interactions — migrated from Oasis CNST's
-- client-side 117-entry DB (js/dni.js) so every app in the ecosystem shares
-- one copy instead of each bundling its own. Safe to re-run (IF NOT EXISTS
-- throughout). Seed via POST /drug-interactions/bulk after this runs — see
-- scripts/drug_nutrient_interactions_seed.json (117 rows, ready to paste
-- into {"items": [...]})

create table if not exists public.drug_nutrient_interactions (
  id bigint generated by default as identity primary key,

  -- Stable slug from the source dataset (e.g. "warfarin"). NOT unique —
  -- two source drugs (metformin, sulfonylureas) had a second, more detailed
  -- entry under the same slug; both are kept as separate rows, distinguished
  -- by drug/subcategory, rather than merging or dropping one.
  external_id text not null,

  drug         text not null,          -- display name, e.g. "Warfarin (Coumadin)"
  aliases      text[] default '{}',    -- generic/brand names, lowercased, for search
  category     text,                   -- e.g. "Cardiovascular"
  subcategory  text,                   -- e.g. "Anticoagulant — Vitamin K Antagonist"
  effects      text[] default '{}',    -- drug/nutrient effect bullet points
  implications text[] default '{}',    -- nutritional implications & cautions
  severity     text,                   -- info | caution | moderate | major
  tags         text[] default '{}',    -- search/filter keywords

  source     text default 'oasis_cnst_migration',
  created_at timestamptz not null default now()
);

comment on table public.drug_nutrient_interactions is
  'Drug-nutrient interaction reference data, migrated from Oasis CNST js/dni.js. Sources: Krause & Mahan''s Food and the Nutrition Care Process 16th ed.; The Essential Pocket Guide for Clinical Nutrition 4th ed.; LPI/OSU Micronutrient Info Center; NIH PMC6109862. Clinical reference only — not a substitute for a current pharmacopoeia or per-patient interaction checker.';

create index if not exists idx_dni_drug on public.drug_nutrient_interactions (lower(drug));
create index if not exists idx_dni_category on public.drug_nutrient_interactions (category);
create index if not exists idx_dni_severity on public.drug_nutrient_interactions (severity);
create index if not exists idx_dni_aliases on public.drug_nutrient_interactions using gin (aliases);
create index if not exists idx_dni_tags on public.drug_nutrient_interactions using gin (tags);
